#https://github.com/YMonnier/ProBill
language: objective-c  #1
osx_image: xcode7.3 #2
xcode_project: ProBill.xcodeproj #3
xcode_scheme: ProBill #4
xcode_sdk: iphonesimulator #5
script:
- xcodebuild -project ProBill.xcodeproj -scheme ProBill -sdk iphonesimulator build test