#https://github.com/YMonnier/ProBill
language: objective-c
osx_image: xcode7.3
xcode_project: ProBill/ProBill.xcodeproj
xcode_scheme: ProBill
xcode_sdk: iphonesimulator
script:
- xcodebuild -project ProBill/ProBill.xcodeproj -scheme ProBill -sdk iphonesimulator