#https://github.com/YMonnier/ProBill
language: objective-c
osx_image: xcode7.3
xcode_project: ProBill/ProBill.xcodeproj
xcode_scheme: ProBill
xcode_sdk: iphonesimulator9.3
podfile: ProBill/Podfile
script:
- xcodebuild clean build test -project ProBill/ProBill.xcodeproj -scheme ProBill GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
#- xcodebuild -project ProBill/ProBill.xcodeproj -scheme ProBill